src/blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('blog', views.PostList.as_view(), name='blog'),
    path('blog/<int:year>/<int:month>/<int:day>/<slug:slug>/', views.post_detail, name='post_detail'),
    path('post_review/<int:pk>', views.post_review, name='post_review'),
]

src/organisations/api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()
router.register(r'organisations/type', views.OrganisationTypeViewSet, basename='organisation_type')

urlpatterns = [
    path('organisations/', views.OrganisationList.as_view(), name="api_organisations"),
    path('organisations/<int:pk>', views.OrganisationDetail.as_view(), name="api_organisation_detail"),
]

urlpatterns += router.urls

src/organisations/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views

urlpatterns = [
    path('new_organisation', views.new_organisation, name='new_organisation'),
    path('edit_organisation/<int:pk>', views.edit_organisation, name='edit_organisation'),
    path('organisation/<int:pk>', views.organisation, name='organisation'),
    path('organisations', views.organisations, name='organisations'),
    path('approve_organisation/<int:pk>/<int:status>', views.approve_organisation, name='approve_organisation'),
    path('delete_organisation/<int:pk>', views.delete_organisation, name='delete_organisation'),
    path('allowUserOrganisation/', views.allowUserOrganisation, name='allowUserOrganisation'),
    url(r'^api/', include('organisations.api.urls')),
]

src/organisations/models.py
from django.conf import settings
from django.contrib.gis.db import models
from django.core.files.storage import default_storage
from django.urls import reverse_lazy as rl
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _
from django_countries.fields import CountryField
from utilities.models import AbstractTranslatedModel

from .managers import OrganisationTypeQuerySet


class OrganisationType(AbstractTranslatedModel):
    type = models.TextField()

    str_field = 'type'

    objects = OrganisationTypeQuerySet.as_manager()

    class Meta:
        verbose_name = _('Organization Type')
        verbose_name_plural = _('Organization Types')
        ordering = ['type']


class Organisation(models.Model):
    name = models.CharField(_('Name'), max_length=200)
    url = models.URLField(max_length=200)
    description = models.CharField(max_length=3000)
    orgType = models.ForeignKey(OrganisationType, on_delete=models.CASCADE, verbose_name=_('Organization Type'))
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                related_name='creator', verbose_name=_('Creator'))
    dateCreated = models.DateTimeField('Created date', auto_now=True)
    dateUpdated = models.DateTimeField('Updated date', auto_now=True)
    logo = models.ImageField(upload_to='images/', max_length=300, null=True, blank=True)
    contactPoint = models.CharField(max_length=100, null=True, blank=True)
    contactPointEmail = models.EmailField(max_length=100, null=True, blank=True)
    latitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    location = models.PointField(blank=True, null=True)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    country = CountryField(null=True, blank=True)
    approved = models.BooleanField(_('Approved'), null=True)

    class Meta:
        verbose_name = _('Organisation')
        verbose_name_plural = _('Organisations')

    def __str__(self):
        return f'{self.name}'

    @property
    def safe_image(self):
        if self.logo and default_storage.exists(self.logo.path):
            return self.logo
        else:
            return 'void_600.png'

    def safe_url(self):
        href = rl('edit_organisation', kwargs={'pk': self.pk})
        return mark_safe(f'<a href="{href}" target="_blank">URL</a>')

    safe_url.allow_tags = True
    safe_url.short_description = 'Site URL'

    def save(self, *args, **kwargs):
        # approved can be null (not moderated), so we can't put self.approved = ... in one line
        if not self.pk and self.creator.is_staff:
            self.approved = True

        super().save(*args, **kwargs)


class OrganisationPermission(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    organisation = models.ForeignKey(Organisation, on_delete=models.CASCADE)

src/organisations/forms.py
from django import forms
from django_select2.forms import Select2MultipleWidget
from django.shortcuts import get_object_or_404
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError

from .models import Organisation, OrganisationType
from projects.forms import getCountryCode
from ckeditor.widgets import CKEditorWidget


class OrganisationForm(forms.Form):
    name = forms.CharField(
        max_length=200,
        label=_('Organisation name'),
        help_text=_('Please write the name of the organisation or network.'),
        widget=forms.TextInput())
    url = forms.URLField(
        max_length=200,
        label=_('URL'),
        help_text=_('Please provide the URL to the website of the organisation.'),
        widget=forms.TextInput())
    description = forms.CharField(
        help_text=_('Please briefly describe the organisation (max 500 words).'),
        widget=CKEditorWidget(config_name='frontpage'),
        label=_('Description'),
        max_length=3000)
    orgType = forms.ModelChoiceField(
        queryset=OrganisationType.objects.none(),
        label=_("Type"),
        help_text=_('Please select one.'),
        widget=forms.Select(attrs={'class': 'js-example-basic-single'}))
    logo = forms.ImageField(
        required=False,
        help_text=_("The image (.jpg or .png) will be resized to 600 x 400 pixels."
                    "Image files with dimensions that greatly differ from this size may be "
                    "drastically cropped. To learn how to avoid this, see our <a href='/"
                    "guide' target='_blank'>User Guide.</a>"),
        widget=forms.FileInput(attrs={'data-image-suffix': '', 'data-image-width-option': 0}))
    x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height = forms.FloatField(widget=forms.HiddenInput(), required=False)
    contact_point = forms.CharField(
        max_length=100,
        help_text=_('Please name the contact person or contact point for the organisation.'),
        label=_('Organisation contact point'),
        widget=forms.TextInput())
    contact_point_email = forms.EmailField(
        max_length=100,
        label=_('Contact point email'),
        help_text=_('Please provide the email address of the contact person or contact point.'),
        widget=forms.TextInput())

    latitude = forms.DecimalField(
        max_digits=9,
        decimal_places=6,
        widget=forms.HiddenInput(),
        required=True)

    longitude = forms.DecimalField(
        max_digits=9,
        decimal_places=6,
        widget=forms.HiddenInput(),
        required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['orgType'].queryset = OrganisationType.objects.translated_sorted_by_text()

    def clean_latitude(self):
        if not self.cleaned_data['latitude']:
            raise ValidationError("A marcação da localização no mapa é obrigatória")

    def save(self, args, logo_path):
        pk = self.data.get('organisationID', '')
        orgType = get_object_or_404(OrganisationType, id=self.data['orgType'])
        if pk:
            organisation = get_object_or_404(Organisation, id=pk)
            organisation.name = self.data['name']
            organisation.url = self.cleaned_data['url']
            organisation.description = self.data['description']
            organisation.orgType = orgType
            organisation.contactPoint = self.data['contact_point']
            organisation.contactPointEmail = self.data['contact_point_email']
            organisation.latitude = self.data['latitude']
            organisation.longitude = self.data['longitude']
            organisation.approved = self.data.get('approved', organisation.approved)
        else:
            organisation = Organisation(
                name=self.data['name'],
                url=self.cleaned_data['url'],
                creator=args.user,
                latitude=self.data['latitude'],
                longitude=self.data['longitude'],
                description=self.data['description'],
                orgType=orgType,
                contactPoint=self.data['contact_point'],
                contactPointEmail=self.data['contact_point_email'])

        if logo_path:
            organisation.logo = logo_path
        country = getCountryCode(organisation.latitude, organisation.longitude)
        organisation.country = country
        organisation.save()
        return organisation


class OrganisationPermissionForm(forms.Form):
    selectedUsers = forms.CharField(widget=forms.HiddenInput(), required=False, initial=())
    usersCollection = forms.CharField(widget=forms.HiddenInput(), required=False, initial=())
    usersAllowed = forms.MultipleChoiceField(
        choices=(),
        widget=Select2MultipleWidget,
        required=False,
        label=_("Give additional users permission to edit"))

src/organisations/api/views.py
from django.http import Http404
from organisations.api.serializers import OrganisationTypeSerializer, OrganisationSerializer, \
    OrganisationSerializerCreateUpdate
from organisations.models import OrganisationType, Organisation
from organisations.views import getCooperators
from rest_framework import viewsets
from rest_framework.permissions import BasePermission
from rest_framework.response import Response
from rest_framework.status import (HTTP_201_CREATED, HTTP_204_NO_CONTENT, HTTP_400_BAD_REQUEST)
from rest_framework.views import APIView


class AdminPermissionsClass(BasePermission):
    def has_permission(self, request, view):
        METHODS_WITH_PERMISSION = ["DELETE", "PUT", "POST"]
        if request.method in METHODS_WITH_PERMISSION:
            return request.user.is_staff
        return True


class PermissionClass(BasePermission):
    def has_permission(self, request, view):
        METHODS_WITH_PERMISSION = ["DELETE", "PUT", "POST"]
        if request.method in METHODS_WITH_PERMISSION:
            return request.user and request.user.is_active
        return True


class OrganisationTypeViewSet(viewsets.ModelViewSet):
    permission_classes = (AdminPermissionsClass,)
    serializer_class = OrganisationTypeSerializer
    queryset = OrganisationType.objects.all()


class OrganisationList(APIView):

    def applyFilters(self, request, organisations):
        country = request.query_params.get('country', None)
        if country is not None:
            organisations = organisations.filter(country=country)

        orgType = request.query_params.get('orgType', None)
        if orgType is not None:
            organisations = organisations.filter(orgType=orgType)

        return organisations

    def get(self, request, format=None):
        organisations = Organisation.objects.all()
        organisations = self.applyFilters(request, organisations)
        serializer = OrganisationSerializer(organisations, many=True, context={'request': request})
        return Response(serializer.data)

    def post(self, request, format=None):
        serializer = OrganisationSerializerCreateUpdate(data=request.data)
        if serializer.is_valid():
            serializer.save(request)
            serializerReturn = OrganisationSerializer(Organisation.objects.get(pk=serializer.data.get('id')),
                                                      context={'request': request})
            return Response(serializerReturn.data, status=HTTP_201_CREATED)
        return Response(serializer.errors, status=HTTP_400_BAD_REQUEST)


class OrganisationDetail(APIView):
    permission_classes = (PermissionClass,)

    def get_object(self, pk):
        try:
            return Organisation.objects.get(pk=pk)
        except Organisation.DoesNotExist:
            raise Http404

    def get(self, request, pk, format=None):
        organisation = self.get_object(pk)
        serializer = OrganisationSerializer(organisation, context={'request': request})
        return Response(serializer.data)

    def put(self, request, pk, format=None):
        organisation = self.get_object(pk)
        if request.user == organisation.creator or request.user.is_staff or request.user.id in getCooperators(pk):
            serializer = OrganisationSerializerCreateUpdate(organisation, data=request.data)
            if serializer.is_valid():
                serializer.update(organisation, serializer.validated_data, request.data)
                serializerReturn = OrganisationSerializer(Organisation.objects.get(pk=serializer.data.get('id')),
                                                          context={'request': request})
                return Response(serializerReturn.data)
        else:
            return Response({"This user can't update this organisation"}, status=HTTP_400_BAD_REQUEST)
        return Response(serializer.errors, status=HTTP_400_BAD_REQUEST)

    def patch(self, request, pk, format=None):
        organisation = self.get_object(pk)
        if request.user == organisation.creator or request.user.is_staff or request.user.id in getCooperators(pk):
            serializer = OrganisationSerializerCreateUpdate(organisation, data=request.data, partial=True)
            if serializer.is_valid():
                serializer.update(organisation, serializer.validated_data, request.data)
                serializerReturn = OrganisationSerializer(Organisation.objects.get(pk=serializer.data.get('id')),
                                                          context={'request': request})
                return Response(serializerReturn.data)
        else:
            return Response({"This user can't update this organisation"}, status=HTTP_400_BAD_REQUEST)
        return Response(serializer.errors, status=HTTP_400_BAD_REQUEST)

    def delete(self, request, pk, format=None):
        organisation = self.get_object(pk)
        if request.user == organisation.creator or request.user.is_staff or request.user.id in getCooperators(pk):
            organisation.delete()
            return Response(status=HTTP_204_NO_CONTENT)
        else:
            return Response({"This user can't delete this organisation"}, status=HTTP_400_BAD_REQUEST)

src/organisations/templates/_delete_modal.html
{% load i18n %}
<div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">{% trans "Confirm delete" %}</h4>
                <button type="button" class="close" data-bs-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
                <p>{% trans "You are going to delete this organisation, this procedure is irreversible." %}</p>
                <p>{% trans "Do you want to proceed?" %}</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-bs-dismiss="modal">{% trans "Cancel" %}</button>
                <a class="btn btn-red btn-delete"><i class="fas fa-trash-alt"></i> {% trans "Delete" %}</a>
            </div>
        </div>
    </div>
</div>

src/organisations/templates/_finder_organisation.html
{% load i18n %}
{% load static %}
{% load countries %}
<div class="row">
    <form class="form-inline float-lg-right" id="searchOrganisations" action="{% url 'organisations' %}">
        <input type="hidden" name="keywords" value="{{filters.keywords}}"/>

        <div class="col-12 d-flex">

            <div id="div-ordenacao">
                <div class="title-filtros">{% trans "Order by" %}</div>
                <div class="input-group input-group-sm filter-bar">
                    <div class="input-group-text filter-img">
                        <img src="{% static '../static/site/icons/order-icon.png' %}" height="14px;" alt="">
                    </div>
                    <select id="orderby" name="orderby" class="custom-select form-control">
                        <option value="-dateUpdated" {% if filters.orderby == "-dateUpdated" %}selected{% endif %}>{% trans "Most Recent" %}</option>
                        <option value="name" {% if filters.orderby == "name" %}selected{% endif %}>{% trans "By Name" %}</option>
                    </select>
                </div>
            </div>


            <div id="div-filtros">
                <div class="title-filtros">{% trans "Filter by" %}</div>
                <div class="input-group input-group-sm filter-bar">

                    <div class="input-group-text filter-img">
                        <img src="{% static '../static/site/icons/filter-icon.png' %}" height="14px;" alt="">
                    </div>

                    <select id="country" name="country" class="custom-select form-control">
                        <option value="">{% trans "Country" %}<option>
                        {% for country in countries %}
                        {% for cwc in countriesWithContent %}
                        {% if country.code == cwc %}
                        <option {% if country.code ==  filters.country %} selected {% endif %} value="{{ country.code }}">
                        {{ country.name }}
                        </option>
                        {% endif %}
                        {% endfor %}
                        {% endfor %}
                    </select>
                    <select id="orgTypes" name="orgTypes" class="custom-select form-control">
                        <option value="">{% trans "Type" %}<option>
                        {% for t in orgTypes %}
                        <option {% if t|safe ==  filters.orgTypes %} selected {% endif %} value="{{t}}">
                        {{t|capfirst}}
                        </option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12 mb-4">
                {% if filters.keywords %}
                <a href="#" class="badge rounded-pill bg-blue3 mt-4 search-filter">
                    <i class="fas fa-times"></i> {% trans "keyword:" %} {{filters.keywords}}
                </a>
                {% endif %}
                {% if filters.country %}
                <a href="#" class="badge rounded-pill bg-blue1 mt-4" id="pill-country">
                    <i class="fas fa-times"></i>
                    {% for country in countries %}
                    {% if country.code == filters.country %}
                    {% trans "country" %}: {{country.name}}
                    {% endif %}
                    {% endfor %}
                </a>
                {% endif %}
                {% if filters.orgTypes %}
                <a href="#" class="badge rounded-pill bg-blue2 mt-4" id="pill-orgTypes">
                    <i class="fas fa-times"></i>
                    {% trans "type:" %} {{filters.orgTypes}}
                </a>
                {% endif %}
                {% if request.get_full_path != "/organisations" %}
                <a class="badge rounded-pill bg-blue3 text-decoration-none mt-4" href="/organisations">
                    <i class="fas fa-times"></i> {% trans "Clear current search query and filters" %}
                </a>
                {% endif %}
                <div class="small result mb-3 mt-3">
                    {{ counter }}
                    {% if counter != 1 %}
                    {% trans "organisations" %}
                    {% else %}
                    {% trans "organisation" %}
                    {% endif %}
                    {% trans "found" %}
                </div>
            </div>
        </div>
    </form>
</div>

src/organisations/templates/_intro_form_organisation.html
{% load i18n %}
<div class="row">
    <div class="col-12">
        {% if organisation.id %}
        <h1>{% trans "Editing" %}<span class="text-blue3"> {{organisation.name}}</span></h1>
        {% else %}
        <h1>{% trans "New" context "fem" %}<span class="text-blue3"> {% trans "organisation" %}</span></h1>
        {% endif %}
        {% if not organisation.id %}
        <div class="row">
            <div class="col-12">
                <div class="small mb-2">{% trans "Thank you for registering your rare health organisation or network on the Saúdes Raras platform. The organisation or network profile can be linked with the personal profiles of the people in your organisation, the profiles of projects that your organisation is involved in, and the resource profiles that were published by your organisation." %}</div>
                <div class="small mb-2">{% trans "Please fill in all mandatory information (indicated with an asterisk*) and as much optional information as possible." %}</div>
                <div class="small mb-2">{% trans "After submitting this form, your organisation or network will undergo moderation by the Saúdes Raras team. This step is simply to prevent use of the platform for purposes other than supporting the health of rare people." %}</div>
                <div class="small mb-2">{% trans "We would like to point out that, upon registration of a document or information, you have to clear the image rights and copyrights of the content you are submitting. Please indicate the author or copyright holder of all pictures and content, when applicable. You may need to obtain express written permission from them." %}</div>
            </div>
        </div>
        {% endif %}
    </div>
</div>

src/organisations/templates/organisation_form.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load thumbnail %}
{% load leaflet_tags %}
{% load crispy_forms_tags %}
{% load eucs_platform_tags %}
{% block head %}
{{block.super }}
<link rel="stylesheet" href="{% static 'styles/jquery-ui.css' %}">
<link rel="stylesheet" href="{% static 'site/css/leaflet-geosearch_3_9.css' %}">
<link rel="stylesheet" href="{% static 'site/css/forms.css' %}">
{% leaflet_js %}
{% leaflet_css %}
{{ form.media.css }}
{{ form.media.js }}

{% endblock head %}

{% block title %}{{ block.super }} :: Edit organisation{% endblock %}


{% block list_of_items %}
{% include '_crop_zone.html' %}
<!-- END MODAL TO CROP -->


<div class="intro-form mt-5 mb-5 pb-5 pt-5">
  <div class="container">
    {% include "_intro_form_organisation.html" %}
  </div>
</div>

<!-- TODO: This form like the others -->
<div class="container mt-5">
    <form
        {% if organisation.id %}
        action="/edit_organisation/{{organisation.id}}"
        {% else %}
        action="/new_organisation"
        {% endif %}
        method="post"
        enctype="multipart/form-data"
        class="edit-organisation"
        autocomplete="off">
        {% csrf_token %}

        <div class="row">
            <div class="col-12">
                <div class="row d-flex justify-content-center">
                    <div class="col-8">
                        <h3 class="leftborder">{% trans "Main information" %}</h3>
                          <input type="hidden" id="organisationID" name="organisationID" value={{organisation.id}}>
                          {{ form.name|as_crispy_field }}
                          {{ form.url|as_crispy_field }}
                          {{ form.description|as_crispy_field }}
                          {{ form.orgType|as_crispy_field }}                            
                    </div>
                </div>
                <div class="row d-flex justify-content-center">                    
                    <div class="col-8">
                        <h3 class="leftborder mt-5">{% trans  "Contact information" %}</h3>
                        {{ form.contact_point|as_crispy_field }}
                        {{ form.contact_point_email|as_crispy_field }}
                    </div>
                </div>
                <div class="row d-flex justify-content-center">                    
                    <div class="col-8">
                        <h3 class="leftborder mt-5">{% trans "Organisation logo" %}</h3>
                          <a id="imgResult" href="#"> <img
                                            class="img-fluid img-zoom"
                                            id="imageResult"
                                            src="{% thumbnail organisation.logo|safe_image 600x400 crop%}"> </a>

                          {{ form.logo|as_crispy_field }}
                          {{ form.x|as_crispy_field }}
                          {{ form.y|as_crispy_field }}
                          {{ form.height|as_crispy_field }}
                          {{ form.width|as_crispy_field }}                            
                    </div>
                </div>
                <div class="row d-flex justify-content-center">                    
                    <div class="col-8">
                        <h3 class="leftborder mt-5">{% trans "Location" %}*</h3>
                        <p id="hint_id_map" class="help-block">{% trans "Locate on the map or inform in the field below the city or region and country of your initiative or organization." %}</p>
                        <p class="help-block"><strong>{{ error }}</strong></p>
                        {% leaflet_map "map" callback="window.map_init_basic" %}
                        {{ form.latitude|as_crispy_field }}
                        {{ form.longitude|as_crispy_field }}
                        <div class="row mt-5 mb-5">
                            <div class="col-11">
                                <button type="submit" class="btn btn-blue3"><i class="fas fa-share-square"></i> {% trans "Save" %}</button>
                            </div>
                        </div>
                        <div class="row mt-5 mb-5">
                            <div class="col-11">
                                {% if user.is_staff and organisation.id and organisation.approved == None %}
                                    <a href="{% url 'approve_organisation' organisation.id 1 %}"
                                       class="btn btn-blue3"><i class="fas fa-thumbs-up"></i> {% trans "Approve" %}
                                    </a>
                                    <a href="{% url 'approve_organisation' organisation.id 0 %}"
                                       class="btn btn-blue3"><i class="fas fa-thumbs-down"></i> {% trans "Do not" %} {% trans "Approve" %}
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock list_of_items %}

{% block scripts %}
<script src="{% static 'scripts/jquery-ui.min.js' %}"></script>
<script src="{% static 'scripts/jquery.ui.touch-punch.min.js' %}"></script>
<script src="{% static 'site/js/site.js' %}"></script>
<script src="{% static 'scripts/cropper.min.js' %}"></script>
<script src="{% static 'scripts/jquery-cropper.min.js' %}"></script>
<script src="{% static 'site/js/leaflet-geosearch_3_9.min.js' %}"></script>
<script src="{% static 'site/js/modal-crop.js' %}?v=1"></script>
<script>

$('form').on('submit', function(e) {
  $("button[type=submit]").attr('disabled','true'); 
});

</script>

<script type="text/javascript">
  var map;
  var coord_lat = $("#id_latitude").val();
  var coord_long = $("#id_longitude").val();
  var marker_layer = new L.marker([50.5, 30.5]);

  function editMarker(e){
    map.removeLayer(marker_layer);
    marker_layer = new L.marker(e.latlng, {draggable:true});
    marker_layer.on('drag', function (e) {
      $("#id_latitude").val((e.latlng.lat).toFixed(6));
      $("#id_longitude").val((e.latlng.lng).toFixed(6));
    });
    map.addLayer(marker_layer);
    $("#id_latitude").val((e.latlng.lat).toFixed(6));
    $("#id_longitude").val((e.latlng.lng).toFixed(6));
  }

  function searchedMarker(e){
    map.removeLayer(marker_layer);
    marker_layer = new L.marker([e.location.y,e.location.x], {draggable:true});
    marker_layer.on('drag', function (e) {
      $("#id_latitude").val((e.latlng.lat).toFixed(6));
      $("#id_longitude").val((e.latlng.lng).toFixed(6));
    });
    map.addLayer(marker_layer);
    $("#id_latitude").val(parseFloat(e.location.y).toFixed(6));
    $("#id_longitude").val(parseFloat(e.location.x).toFixed(6));
  }

  function map_init_basic (leafmap, options) {
    map = leafmap;
    var obj = { latlng: {
      lat: parseFloat($("#id_latitude").val()),
      lng: parseFloat($("#id_longitude").val()) }
    }
    if($("#id_latitude").val() && $("#id_latitude").val() != 0)
    editMarker(obj);
    map.on('click', editMarker);
    if(coord_lat !== null && coord_lat !== "" && coord_lat != 0) {
      map.flyTo([coord_lat, coord_long], 8)
    }

    var GeoSearchControl = window.GeoSearch.GeoSearchControl;
    var OpenStreetMapProvider = window.GeoSearch.OpenStreetMapProvider;
    var provider = new OpenStreetMapProvider({});

    //  Define search controls
    var searchControl = new GeoSearchControl({
      provider: provider,
      style: 'bar',
      showMarker: false,
      autoClose: true,
      keepResult: true,
      //retainZoomLevel: true,
    });

    map.addControl(searchControl);
    map.on('geosearch/showlocation', searchedMarker);
  }
</script>
{{ form.media.js }}
{% endblock scripts %}

src/organisations/templates/organisations.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}{{ block.super }} :: {% trans "Organisations" %}{% endblock %}

{% block list_of_items %}
<div class="container mt-5">
    <div clas="row">
        <div class="col-12">
            <h1>{% trans "organisation or network <span class='text-blue3'>search</span>" %}</h1>
        </div>
        {% include "_subnavbar.html" %}
        {% include "_finder_organisation.html" %}
    </div>
	<div class="row">
    {% if organisations %}
        {% include "organisations_cards.html" %}
    {% endif %}
	</div>
</div>
{% endblock list_of_items %}

{% block scripts %}
<script src="{% static 'site/js/bootstrap-autocomplete.js'%}"></script>
<script>
    $('.basicAutoComplete').autoComplete(
	{ minLength: 3 }
	);

	$('.basicAutoComplete').on('autocomplete.select', function (evt, item) {
		$('#searchOrganisations').submit();
	});

	$(function () {
		$('.custom-select').on('change', function () {
			$('#searchOrganisations').submit();
		});
        $('#pill-country').on('click', function() {
            $('#country').val('')
            $('#searchOrganisations').submit();
        });
        $('#pill-orgTypes').on('click', function() {
            $('#orgTypes').val('')
            $('#searchOrganisations').submit();
        });

	});
</script>
{% endblock scripts %}